
# Generated by CodiumAI
from src.main import main
import pygments
from src.main import main_menu
from src.gui import GUI


import pytest

class TestMain:

    # Initializes pygame and sets up a window with a caption
    def test_initialization(self):
        main()
        assert pygame.display.get_caption() == "Intelligent Game of Life"

    # Calls main_menu function to get a game object
    def test_main_menu(self):
        main()
        assert main_menu(pygame.display.set_mode((800, 600))) is not None

    # Initializes a GUI object with the game object
    def test_gui_initialization(self):
        main()
        game = main_menu(pygame.display.set_mode((800, 600)))
        gui = GUI(game)
        assert gui.game == game

    # User closes the window before selecting a game, which should return None and exit the program
    def test_window_close(self):
        main()
        assert main_menu(pygame.display.set_mode((800, 600))) is None

    # User selects an invalid option in the main menu, which should return None and exit the program
    def test_invalid_option(self):
        main()
        assert main_menu(pygame.display.set_mode((800, 600))) is None

    # User resizes the window during the game, which should update the GUI to fit the new dimensions
    def test_window_resize(self):
        main()
        game = main_menu(pygame.display.set_mode((800, 600)))
        gui = GUI(game)
        pygame.display.set_mode((400, 300))
        assert gui.screen.get_size() == (400, 300)
